addr: 127.0.0.1:51680
autoLaunch: false
autoReport: false
language: zh-CN
localHTTPToken: 938d88c3119a6f52ea6aabbd0b02a6d9
proxyAll: false
socksAddr: 127.0.0.1:51683
systemProxy: true
uiAddr: localhost:51678
userID: 134277286
userToken: N5F4dxo63GTZIl6NMohq7EPjKje5KaWax5KjogML5F7f6Fu95SwSiA
